server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/profile-management
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
    validationQuery: "SELECT 1"
  jpa:
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        show-sql: false
        use_sql_comments: false
        format_sql: false
    database: postgresql
  sql:
    init:
      platform: postgres
